name: Ubuntu GCC Build

on:
  push:
    branches:
      - master-qt6
  pull_request:
    branches:
      - master-qt6
  workflow_dispatch: 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ubuntu-gcc
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master-qt6'
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake qt6-base-dev

    - name: Build Protobuf
      shell: bash
      run: |
        chmod +x ./CI/build_protobuf.sh
        sudo ./CI/build_protobuf.sh

    - name: Configure CMake
      shell: bash
      run: cmake -B build -G "Unix Makefiles"

    - name: Build project
      shell: bash
      run: |
        cmake --build build --config Debug --parallel $(nproc)

        echo "Dependencies for shader-gen"
        ldd build/shader-gen

        echo "Dependencies for shader-gen-tests"
        ldd build/shader-gen-tests

    - name: Run tests
      shell: bash
      run: ctest --test-dir build --parallel $(nproc) --output-on-failure --verbose -C Debug
