name: Ubuntu GCC Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ubuntu-gcc
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake qtbase5-dev

    - name: Fetch Abseil and Protobuf latest tags
      run: |
        ABSL_LATEST_TAG=$(git ls-remote --tags https://github.com/abseil/abseil-cpp.git | grep -o 'refs/tags/[^{}]*$' | sort -t '/' -k 3 -V | tail -n1 | awk -F/ '{print $3}')
        PROTOBUF_LATEST_TAG=$(git ls-remote --tags https://github.com/protocolbuffers/protobuf.git | grep -o 'refs/tags/[^{}]*$' | sort -t '/' -k 3 -V | tail -n1 | awk -F/ '{print $3}')

        echo "ABSL_LATEST_TAG=$ABSL_LATEST_TAG" >> $GITHUB_ENV
        echo "PROTOBUF_LATEST_TAG=$PROTOBUF_LATEST_TAG" >> $GITHUB_ENV

        echo "ABSL_LATEST_TAG: $ABSL_LATEST_TAG"
        echo "PROTOBUF_LATEST_TAG: $PROTOBUF_LATEST_TAG"

    - name: Build Abseil
      run: |
        chmod +x CI/build_shared_absl.sh
        bash ./CI/build_shared_absl.sh $ABSL_LATEST_TAG

    - name: Build Protobuf
      run: |
        chmod +x CI/build_shared_protobuf.sh
        bash ./CI/build_shared_protobuf.sh $PROTOBUF_LATEST_TAG

    - name: Configure CMake
      run: |
        mkdir -p build/gui/model/schema build/tests/gui/model/schema
        cmake -B build -G "Unix Makefiles"

    - name: Build project
      run: cmake --build build --config Debug # --parallel $(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --parallel $(nproc) --output-on-failure --verbose -C Debug
