name: Windows GCC Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows-gcc
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: recursive

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-qt5-base
          mingw-w64-x86_64-protobuf
          make
          cmake

    - name: Configure CMake
      shell: msys2 {0}
      run: |
        ls -a
        echo "====================="
        mkdir -p build/gui/model/schema build/tests/gui/model/schema
        cd build
        ls -a
        cd ..
        cmake -B build -G "Unix Makefiles"

    - name: Build project
      shell: msys2 {0}
      run: cmake --build build --config Debug # --parallel $(nproc)

    - name: Run tests
      shell: msys2 {0}
      run: |
        cd build
        ctest --parallel $(nproc) --output-on-failure --verbose -C Debug
