name: Windows GCC Build and Release

on:
  workflow_run:
    workflows:
      - "Windows GCC Build"
    types:
      - completed
    branches: [master-qt6]
  workflow_dispatch:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows-gcc
  cancel-in-progress: true

jobs:
  release:
    runs-on: windows-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'master-qt6'
          submodules: recursive
  
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-python
            git
          path-type: inherit

      - name: Cache Qt6
        id: cache-qt6
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/qt6-lib-static
          key: qt6-${{ runner.os }}-${{ hashFiles('CI/build_qt6_win64_gcc.sh') }}
          restore-keys: |
            qt6-${{ runner.os }}-

      - name: Build Qt6
        if: steps.cache-qt6.outputs.cache-hit != 'true'
        shell: msys2 {0}
        run: |
          ./CI/build_qt6_win64_gcc.sh Release Static "${{ github.workspace }}/qt6-lib-static"

      - name: Cache Protobuf
        id: cache-protobuf
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/protobuf-lib-static
          key: protobuf-${{ runner.os }}-${{ hashFiles('CI/build_protobuf_win64_gcc.sh') }}
          restore-keys: |
            protobuf-${{ runner.os }}-

      - name: Build Protobuf
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        shell: msys2 {0}
        run: |
          mkdir -p "${{ github.workspace }}/protobuf-lib-static"
          echo "Protobuf: '${{ github.workspace }}/protobuf-lib-static'"
          ./CI/build_protobuf_win64_gcc.sh Release Static "${{ github.workspace }}/protobuf-lib-static"

      - name: Populate PATH for 'windeployqt'
        shell: msys2 {0}
        run: |
          echo "${{ github.workspace }}/qt6-lib-static/bin" >> $GITHUB_PATH
  
      - name: Configure CMake
        shell: msys2 {0}
        run: cmake -B build -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM=mingw32-make -DCMAKE_BUILD_TYPE=Release -DSHADER_GEN_LINK_STATIC=ON -DCMAKE_PREFIX_PATH="${{ github.workspace }}/qt6-lib-static/lib/cmake;${{ github.workspace }}/protobuf-lib-static/lib/cmake" -DSHADER_GEN_BUILD_PORTABLE_RELEASE_PACKAGE=ON
  
      - name: Build shader-gen
        shell: msys2 {0}
        run: |
          cmake --build build --config Release --parallel $(nproc)
          echo "Dependencies for shader-gen.exe"
          ldd build/shader-gen

      - name: Create portable package
        shell: msys2 {0}
        run: |
          cpack --config CPackConfig.cmake -G ZIP --verbose -C Release
        working-directory: build
        
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
          tag_name: latest-qt6
          generate_release_notes: true
          draft: false
          token: ${{ secrets.SHADER_GEN_RELEASES_TOKEN }}
        