name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows-msvc
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}'
        setup-python: 'false'

    - name: Build Protobuf
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path "${{ github.workspace }}\protobuf-lib"
        Write-Output "Protobuf: '${{ github.workspace }}\protobuf-lib'"
        Write-Output "Qt5: $env:Qt5_DIR"
        .\CI\build_protobuf_win64.ps1 Debug Dynamic "${{ github.workspace }}\protobuf-lib"

    - name: Configure CMake
      shell: pwsh
      run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="$env:Qt5_DIR;${{ github.workspace }}\protobuf-lib\lib\cmake" -DSHADER_GEN_BUILD_TESTS=ON

    - name: Build project
      shell: pwsh
      run: cmake --build build --config Debug --parallel $env:NUMBER_OF_PROCESSORS

    - name: Copy DLLs next to the executable
      shell: pwsh
      run: |
        cp build\bin\Debug\*.dll build\Debug\
        cp "${{ github.workspace }}\protobuf-lib\bin\*.dll" build\Debug\

    - name: Run tests
      shell: pwsh
      run: ctest --test-dir build --parallel $env:NUMBER_OF_PROCESSORS --output-on-failure --verbose -C Debug
