name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows-msvc
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}'
        setup-python: 'false'

    - name: Build Protobuf
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path "${{ github.workspace }}\protobuf-lib"
        Write-Output "Protobuf: '${{ github.workspace }}\protobuf-lib'"
        ls "${{ github.workspace }}\protobuf-lib"
        Write-Output "============================================="
        ls "${{ github.workspace }}\protobuf-lib\lib"
        Write-Output "============================================="
        ls "${{ github.workspace }}\protobuf-lib\lib\cmake"
        Write-Output "============================================="
        Write-Output "Qt5: $env:Qt5_DIR"
        .\CI\build_protobuf.ps1 `
          -protobuf_prefix "${{ github.workspace }}\protobuf-lib"

    - name: Configure CMake
      shell: pwsh
      run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=$env:Qt5_DIR;"${{ github.workspace }}\protobuf-lib\lib\cmake"

    - name: Build project
      shell: pwsh
      run: cmake --build build --config Debug --parallel $(nproc)

    - name: Run tests
      shell: pwsh
      run: ctest --test-dir build --parallel $(nproc) --output-on-failure --verbose -C Debug
