name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows-msvc
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Build Protobuf
      shell: pwsh
      run: |
        mkdir -p $env:GITHUB_WORKSPACE/abseil-lib
        mkdir -p $env:GITHUB_WORKSPACE/protobuf-lib
        echo "Abseil: $env:GITHUB_WORKSPACE/abseil-lib"
        echo "Protobuf: $env:GITHUB_WORKSPACE/protobuf-lib"
        build_protobuf.ps1 `
          -absl_prefix $env:GITHUB_WORKSPACE/abseil-lib `
          -protobuf_prefix $env:GITHUB_WORKSPACE/protobuf-lib

    - name: Configure CMake
      shell: pwsh
      run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=$env:Qt5_DIR;$env:GITHUB_WORKSPACE/abseil-lib/lib/cmake;$env:GITHUB_WORKSPACE/protobuf-lib/lib/cmake

    - name: Build project
      shell: pwsh
      run: cmake --build build --config Debug --parallel $(nproc)

    - name: Run tests
      shell: pwsh
      run: ctest --test-dir build --parallel $(nproc) --output-on-failure --verbose -C Debug
