name: Windows Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'master'
          submodules: recursive
  
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}'
          setup-python: 'false'

      - name: Download patched windeployqt for MSVC2022
        shell: pwsh
        run: |
          Write-Output "Original Qt5_DIR: $env:Qt5_DIR"
          $qtCMakeDir = $env:Qt5_DIR
          $qtLibDir = Split-Path $qtCMakeDir -Parent
          $qtRootDir = Split-Path $qtLibDir -Parent
          $qtBinDir = Join-Path $qtRootDir "bin"
          Write-Output "Derived Qt bin directory: $qtBinDir"
          
          # Ensure the bin directory exists
          if (-Not (Test-Path $qtBinDir)) {
              New-Item -ItemType Directory -Force -Path $qtBinDir | Out-Null
          }
          
          Write-Output "Downloading patched windeployqt64releaseonly.zip..."
          $zipPath = Join-Path $qtBinDir "windeployqt64releaseonly.zip"
          $retryCount = 3
          $success = $false
          for ($i = 1; $i -le $retryCount; $i++) {
              try {
                  Invoke-WebRequest -Uri "http://tripleboot.org/Uploads/windeployqt64releaseonly.zip" -OutFile $zipPath -UseBasicParsing
                  $success = $true
                  break
              } catch {
                  Write-Output "Download attempt $i of $retryCount failed: $_"
                  Start-Sleep -Seconds 5
              }
          }
          if (-not $success) {
              Write-Error "Failed to download patched windeployqt64releaseonly.zip after $retryCount attempts."
              exit 1
          }
          
          Write-Output "Extracting patched executable into $qtBinDir..."
          Expand-Archive -Path $zipPath -DestinationPath $qtBinDir -Force

      - name: Build Protobuf
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "${{ github.workspace }}\protobuf-lib-static"
          Write-Output "Protobuf: '${{ github.workspace }}\protobuf-lib-static'"
          Write-Output "Qt5: $env:Qt5_DIR"
          .\CI\build_protobuf_win64.ps1 Release Static "${{ github.workspace }}\protobuf-lib-static"

      - name: Configure CMake
        shell: pwsh
        run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="$env:Qt5_DIR;${{ github.workspace }}\protobuf-lib-static\lib\cmake" -DCMAKE_BUILD_TYPE=Release -DSHADER_GEN_LINK_STATIC=ON -DSHADER_GEN_BUILD_PORTABLE_RELEASE_PACKAGE=ON
    
      - name: Build project
        shell: pwsh
        run: cmake --build build --config Release --parallel $env:NUMBER_OF_PROCESSORS

      - name: Create portable package
        shell: pwsh
        run: |
          cpack --config CPackConfig.cmake -G ZIP --verbose -C Release
        working-directory: build
        
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
          tag_name: latest
          generate_release_notes: true
          draft: false
          token: ${{ secrets.SHADER_GEN_RELEASES_TOKEN }}
        